name: uefi-fw-tools # the name of the snap
version: 1.5.4-0.7.2+git # the version of the snap
summary: UEFI Firmware update tools # 79 char long summary
description: # A longer description for the snap
    uefi-fw-tools is a snap for UEFI firmware tool, currently include fwupd.

    fwupd is a daemon to allow session software to update device firmware.
    You can either use a GUI software manager like GNOME Software to view and
    apply updates, the command-line tool or the system D-Bus interface directly.
    Currently, firmware updates using the UEFI capsule format and for the
    ColorHug are supported. More formats may be supported in the future.
    See <https://github.com/hughsie/fwupd> for details
grade: stable
confinement: strict

apps:
    fwupdmgr:
        command: bin/fwupdmgr.sh
        plugs: [network,fwupdmgr] #network plug for sendmmsg
    fwupd:
        command: bin/fwupd.sh
        daemon: simple
        slots: [fwupd]

plugs:
  fwupdmgr:
    interface: fwupd

slots:
  fwupd:
    interface: fwupd
  fwupd-data:
    content: fwupd-data
    interface: content
    write:
      - $SNAP_DATA

parts:
    libefivar-dev:
        plugin: make
        source: https://github.com/lyoncore/efivar.git
        source-type: git
        source-branch: efivar-udev
        build-packages:
          - libpopt-dev
        organize:
          usr/lib64: usr/lib/x86_64-linux-gnu
    libefivar-fixpkgconfig:
        plugin: make
        source: libefivar-fixpkgconfig
        make-parameters:
          - SNAPCRAFT_STAGE=$SNAPCRAFT_STAGE
        after: [libefivar-dev]
    libfwup-dev:
        plugin: make
        source: https://github.com/lyoncore/fwupdate.git
        source-type: git
        make-parameters:
          - EFIDIR=ubuntu
          - GNUEFIDIR=/usr/lib
          - LIBDIR=$SNAPCRAFT_STAGE/usr/lib/x86_64-linux-gnu
          - libdir=/usr/lib/x86_64-linux-gnu
          - PKG_CONFIG_PATH=$SNAPCRAFT_STAGE/usr/lib/x86_64-linux-gnu/pkgconfig
          - --eval=export PKG_CONFIG_PATH
        build-packages:
          - elfutils
          - gnu-efi
          - libasm1
          - libdw1
          - libefivar-dev
          - libsmbios-dev
          - libsmbios2v5
        after: [libefivar-fixpkgconfig]
    appstream-glib-dev:
        plugin: autotools
        source: https://github.com/lyoncore/appstream-glib.git
        source-type: git
        source-branch: uefi-fw-tools-uc16-snap_0_5_X
        build-packages:
          - intltool
          - libarchive-dev
          - libgcab-dev
          - libgdk-pixbuf2.0-dev
          - libgirepository1.0-dev
          - libglib2.0-dev
          - libgtk-3-dev
          - libjson-glib-dev
          - libsoup2.4-dev
          - libsqlite3-dev
          - libyaml-dev
          - uuid-dev
          - xmlto
        configflags:
          - --disable-gtk-doc
          - --disable-gtk-doc-html
          - --disable-gtk-doc-pdf
          - --prefix=/usr
        after: [libfwup-dev]
    fwupd:
        plugin: autotools
        source: https://github.com/lyoncore/fwupd.git
        source-type: git
        source-branch: uefi-fw-tools-uc16-snap
        build-packages:
          - docbook-utils
          - gettext
          - intltool
          - libarchive-dev
          - libcolord-dev
          - libgcab-dev
          - gcab
          - libgirepository1.0-dev
          - libglib2.0-dev
          - libgpgme11-dev
          - gnupg2
          - libtool-bin
          - libgudev-1.0-dev
          - udev
          - libgusb-dev
          - libpolkit-gobject-1-dev
          - libsqlite3-dev
          - pkg-config
          - libsoup2.4-dev
          - gtk-doc-tools
          - libcolorhug-dev
          - valgrind
          - libsmbios-dev
          - libgdk-pixbuf2.0-dev
        stage-packages:
          - glib-networking
          - gnupg
        configflags:
          - --disable-gtk-doc
          - --disable-gtk-doc-html
          - --disable-gtk-doc-pdf
          - UEFI_CFLAGS=-I$SNAPCRAFT_STAGE/usr/include
          - UEFI_LIBS=-L$SNAPCRAFT_STAGE/usr/lib/x86_64-linux-gnu/ -lfwup -lefivar -lefiboot
          - APPSTREAM_GLIB_CFLAGS=-I$SNAPCRAFT_STAGE/usr/include/libappstream-glib -I$SNAPCRAFT_STAGE/usr/include/libappstream-builder -I/usr/include/gdk-pixbuf-2.0
          - APPSTREAM_GLIB_LIBS=-L$SNAPCRAFT_STAGE/usr/lib/ -lappstream-glib
        after: [appstream-glib-dev]
    update-mime:
        plugin: make
        source: update-mime
        stage-packages:
          - shared-mime-info
          - gsettings-desktop-schemas
          - libxml2
        after: [fwupd]
    startup-wrapper:
        plugin: dump
        source: startup-wrapper
        organize:
          fwupd.sh: bin/fwupd.sh
          fwupdmgr.sh: bin/fwupdmgr.sh
        after: [update-mime]
